# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_queries', '0002_auto_20181117_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='duplication_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
