# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_queries', '0003_sqlquery_duplication_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sqlquery',
            old_name='duplication_count',
            new_name='duplicate_count',
        ),
    ]
