# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_queries', '0004_auto_20181117_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='similar_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
