# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-18 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('repeat_queries', '0005_sqlquery_similar_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
